Portfolo contact form mobileversion
siddghosh108/Portfolio pull request #2
Opened 2023-05-09 13:05 UTC by siddghosh108

Added the contact form section

2023-05-09 13:27 UTC, levy002 requested changes
## Hello @siddghosh108   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Highlights
- No linter error :heavy_check_mark: 

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-09 13:27 UTC, levy002 commented on index.html
> +  </footer>
- [ ] Kindly make sure to add the background image in order to match the provided Figma design as much as possible.

  - ### YOUR DESIGN
  
   ![image](https://github.com/siddghosh108/Portfolio/assets/87197412/cd41f573-2567-48af-b431-022a9acbcbbe)

  - ### FIGMA DESIGN
  
   ![image](https://github.com/siddghosh108/Portfolio/assets/87197412/0eeda1ae-bd00-4bd3-87b6-c15f78befee2)

2023-05-09 13:27 UTC, levy002 commented on index.html
> +          </div>
- [ ] Kindly make sure to align the `Get in Touch`  button as it is on the provided Figma design as much as possible.

   - ### FIGMA DESIGN
   
    ![image](https://github.com/siddghosh108/Portfolio/assets/87197412/254104fb-e4d0-4dc1-bd33-6fac5da79c68)

   - ### YOUR DESIGN
   
    ![image](https://github.com/siddghosh108/Portfolio/assets/87197412/eff34217-134c-4581-88ce-a2b6914fef09)

2023-05-09 18:23 UTC, KanzaTahreem reviewed
# INVALID ❌ 

Hi @siddghosh108 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code. 😓

## Invalid Code Review Request ❌
- [ ] Unfortunately, you have submitted a pull request with failing linters. Please make sure that all linters are passing and a tick mark ✔ is present.

_**Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready**_ 🤝🙏

Cheers and Happy coding!👏👨‍💻💻

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-10 07:37 UTC, osamaashraf6 approved these changes
Hi @siddghosh108 👋, 
# STATUS: APPROVED! 🥇🟢🟢💯 
<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

Your project is complete!  There is nothing else to say other than... it's time to merge it : ship it: 
Congratulations! 🎉 

## Highlights💯🎈🪄✔️


- [x] No linter errors. ✔️
- [x] Good usage in correcting GitHub flow.✔️
- [x] Nice design.✔️


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-10 13:26 UTC, merged

2023-07-11 11:21 UTC, ichala reviewed
Hi Student  ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
 
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# To Highlight 💪🏻

- Project Already approved✔️ 


 Good job implementing the requirements  :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Optional Suggestions  :

- N/A


**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._